"""Добавлено поле role

Revision ID: 504b5f4adfc8
Revises: 
Create Date: 2021-07-15 12:57:34.248625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504b5f4adfc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_information',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('genre', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('user_general_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_general_information_nickname'), 'user_general_information', ['nickname'], unique=True)
    op.create_index(op.f('ix_user_general_information_role'), 'user_general_information', ['role'], unique=False)
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('description_as_author', sa.Text(), nullable=True),
    sa.Column('purpose_as_author', sa.Text(), nullable=True),
    sa.Column('discord', sa.String(length=50), nullable=True),
    sa.Column('prime_time', sa.String(length=50), nullable=True),
    sa.Column('post_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_general_information.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('response_status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_general_information.id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_response')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_general_information_role'), table_name='user_general_information')
    op.drop_index(op.f('ix_user_general_information_nickname'), table_name='user_general_information')
    op.drop_table('user_general_information')
    op.drop_table('game_information')
    # ### end Alembic commands ###
